@server=http://localhost:4004
@username=alice
@password=


### Books
# @name Books_GET
GET {{server}}/admin/Books
Authorization: Basic {{username}}:{{password}}


### Books
# @name Books_POST
POST {{server}}/admin/Books
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "82744791-d28e-4511-a519-4a2531bd1da0",
  "title": "title-8274479",
  "genre": 1,
  "publCountry": {
    "code": "712"
  },
  "stock": 26,
  "price": {
    "amount": 72.35,
    "currency": {
      "code": "292"
    }
  },
  "isHardcover": false,
  "author": {
    "ID": "23595437-dc4d-4895-ba76-c43f5fe18ac7"
  },
  "createdAt": "2015-02-10T03:00:00.000Z",
  "createdBy": "createdBy.4xcmn@example.net",
  "modifiedAt": "2015-07-20T03:00:00.000Z",
  "modifiedBy": "modifiedBy.4xcmn@example.net"
}


### Books
# @name Books_PATCH
PATCH {{server}}/admin/Books/82744791-d28e-4511-a519-4a2531bd1da0
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "82744791-d28e-4511-a519-4a2531bd1da0",
  "title": "title-8274479",
  "genre": 1,
  "publCountry": {
    "code": "712"
  },
  "stock": 26,
  "price": {
    "amount": 72.35,
    "currency": {
      "code": "292"
    }
  },
  "isHardcover": false,
  "author": {
    "ID": "23595437-dc4d-4895-ba76-c43f5fe18ac7"
  },
  "createdAt": "2015-02-10T03:00:00.000Z",
  "createdBy": "createdBy.4xcmn@example.net",
  "modifiedAt": "2015-07-20T03:00:00.000Z",
  "modifiedBy": "modifiedBy.4xcmn@example.net"
}


### Books
# @name Books_DELETE
DELETE {{server}}/admin/Books/82744791-d28e-4511-a519-4a2531bd1da0
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Authors
# @name Authors_GET
GET {{server}}/admin/Authors
Authorization: Basic {{username}}:{{password}}


### Authors
# @name Authors_POST
POST {{server}}/admin/Authors
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "23595437-dc4d-4895-ba76-c43f5fe18ac7",
  "name": "name-23595437",
  "dateOfBirth": "2012-05-16",
  "dateOfDeath": "2010-01-29",
  "epoch": {
    "ID": 27254491
  },
  "createdAt": "2001-06-02T03:00:00.000Z",
  "createdBy": "createdBy.e1qct@example.com",
  "modifiedAt": "2020-12-10T03:00:00.000Z",
  "modifiedBy": "modifiedBy.e1qct@example.net"
}


### Authors
# @name Authors_PATCH
PATCH {{server}}/admin/Authors/23595437-dc4d-4895-ba76-c43f5fe18ac7
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "23595437-dc4d-4895-ba76-c43f5fe18ac7",
  "name": "name-23595437",
  "dateOfBirth": "2012-05-16",
  "dateOfDeath": "2010-01-29",
  "epoch": {
    "ID": 27254491
  },
  "createdAt": "2001-06-02T03:00:00.000Z",
  "createdBy": "createdBy.e1qct@example.com",
  "modifiedAt": "2020-12-10T03:00:00.000Z",
  "modifiedBy": "modifiedBy.e1qct@example.net"
}


### Authors
# @name Authors_DELETE
DELETE {{server}}/admin/Authors/23595437-dc4d-4895-ba76-c43f5fe18ac7
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Countries
# @name Countries_GET
GET {{server}}/admin/Countries
Authorization: Basic {{username}}:{{password}}


### Currencies
# @name Currencies_GET
GET {{server}}/admin/Currencies
Authorization: Basic {{username}}:{{password}}


### Epochs
# @name Epochs_GET
GET {{server}}/admin/Epochs
Authorization: Basic {{username}}:{{password}}
