@server=http://localhost:4004
@username=alice
@password=


### Books
# @name Books_GET
GET {{server}}/admin/Books
Authorization: Basic {{username}}:{{password}}


### Books
# @name Books_POST
POST {{server}}/admin/Books
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "12784023-0481-4231-8891-fd69ea389e6e",
  "title": "title-12784023",
  "genre": 2,
  "publCountry": {
    "code": "551"
  },
  "stock": 94,
  "price": {
    "amount": 40.22,
    "currency": {
      "code": "333"
    }
  },
  "isHardcover": false,
  "author": {
    "ID": "28409932-64b6-42c2-b4f6-cccdba6fbb75"
  },
  "createdAt": "2002-04-20T03:00:00.000Z",
  "createdBy": "createdBy.7m07r@example.com",
  "modifiedAt": "2017-06-29T03:00:00.000Z",
  "modifiedBy": "modifiedBy.7m07r@example.net"
}


### Books
# @name Books_PATCH
PATCH {{server}}/admin/Books/12784023-0481-4231-8891-fd69ea389e6e
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "12784023-0481-4231-8891-fd69ea389e6e",
  "title": "title-12784023",
  "genre": 2,
  "publCountry": {
    "code": "551"
  },
  "stock": 94,
  "price": {
    "amount": 40.22,
    "currency": {
      "code": "333"
    }
  },
  "isHardcover": false,
  "author": {
    "ID": "28409932-64b6-42c2-b4f6-cccdba6fbb75"
  },
  "createdAt": "2002-04-20T03:00:00.000Z",
  "createdBy": "createdBy.7m07r@example.com",
  "modifiedAt": "2017-06-29T03:00:00.000Z",
  "modifiedBy": "modifiedBy.7m07r@example.net"
}


### Books
# @name Books_DELETE
DELETE {{server}}/admin/Books/12784023-0481-4231-8891-fd69ea389e6e
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Authors
# @name Authors_GET
GET {{server}}/admin/Authors
Authorization: Basic {{username}}:{{password}}


### Authors
# @name Authors_POST
POST {{server}}/admin/Authors
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "name": "name-28409932",
  "dateOfBirth": "2015-12-04",
  "dateOfDeath": "2013-08-01",
  "epoch": {
    "ID": 9690176
  },
  "createdAt": "2005-10-01T03:00:00.000Z",
  "createdBy": "createdBy.gwx8s@example.org",
  "modifiedAt": "2022-08-04T03:00:00.000Z",
  "modifiedBy": "modifiedBy.gwx8s@example.net"
}


### Authors
# @name Authors_PATCH
PATCH {{server}}/admin/Authors/ae8ec880-5185-403e-a802-7078b2669154
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "ae8ec880-5185-403e-a802-7078b2669154",
  "name": "migas",
  "dateOfBirth": "2015-12-04",
  "dateOfDeath": "2011-08-01",
  "epoch": {
    "ID": 9690176
  },
  "createdAt": "2005-10-01T03:00:00.000Z",
  "createdBy": "createdBy.gwx8s@example.org",
  "modifiedAt": "2022-08-04T03:00:00.000Z",
  "modifiedBy": "modifiedBy.gwx8s@example.net"
}


### Authors
# @name Authors_DELETE
DELETE {{server}}/admin/Authors/28409932-64b6-42c2-b4f6-cccdba6fbb75
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Countries
# @name Countries_GET
GET {{server}}/admin/Countries
Authorization: Basic {{username}}:{{password}}


### Currencies
# @name Currencies_GET
GET {{server}}/admin/Currencies
Authorization: Basic {{username}}:{{password}}


### Epochs
# @name Epochs_GET
GET {{server}}/admin/Epochs
Authorization: Basic {{username}}:{{password}}
