@server=http://localhost:4004
@username=alice
@password=


### Books
# @name Books_GET
GET {{server}}/cat/Books
Authorization: Basic {{username}}:{{password}}


### Authors
# @name Authors_GET
GET {{server}}/cat/Authors
Authorization: Basic {{username}}:{{password}}


### Currencies
# @name Currencies_GET
GET {{server}}/cat/Currencies
Authorization: Basic {{username}}:{{password}}


### Epochs
# @name Epochs_GET
GET {{server}}/cat/Epochs
Authorization: Basic {{username}}:{{password}}


### submitOrder
# @name submitOrder_POST
POST {{server}}/cat/submitOrder
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "book": "4062307b-51fc-470c-83c8-e871966a435e",
  "quantity": 29
}
